### ISSUE TITLE
Warning: Sublexicons defined but not used

### ISSUE THREAD

**Issue by albbas** [giellalt/lang-myv#2] opened 2021-03-11 20:22 UTC
Chiara fekk same feil i mdf på måndag (jf https://giella.zulipchat.com/#narrow/stream/238727-mdf/topic/Kompilering.20feil) - det viste seg at ho ikkje hadde oppdatert giella-shared. Kan det vera tilfelle her òg? @Trondtr @albbas ?

_Originally posted by @snomos in https://github.com/giellalt/lang-myv/issues/1#issuecomment-796989025_

**Comment by snomos** [comment] 2021-08-10 10:47
I am not able to reproduce - @rueter do you have any issues building MYV? If not, could you close this issue? 🙂

**Comment by rueter** [comment] 2021-08-10 13:51
No build error is apparent on my mac with myv.

**Closed by rueter** 2021-08-10 13:51 UTC
